version: "3.81"

services:
  web:
    build: .
    command: python mysite/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  #   depends_on:
  #     - db
  # db:
  #   image: some-mysql1
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=my-secret-pw



