from django.urls import path, include
from . import views

urlpatterns = [
    path('latest_errorcode/', views.latest_errorcode, name='test'),
    path('model_keyword/', views.historical_keyword, name='model_keyword'),
    # path('onsite/', views.latest_onsite, name='onsite_repair'),
    path('latest_keyword/', views.latest_keyword, name='keyword_summary'),
    path('defect/', views.historical_errorcode, name='defect_classification'),
    path('classification/', views.latest_errorcode, name='model_classification'),
    path('osr/', views.historical_onsite, name='osr'),
    path('', views.user_manual),
    path('parse_excel/', views.ParseExcel.as_view(), name='parse_excel'),
    path('export/xls/', views.export_xls, name='export'),
    path('export/error/', views.export_error, name='export_error'),
    path('export_latest_keyword_summary_data', views.export_latest_keyword_summary_data, name='export_latest_keyword_summary_data'),
    path('export_historical_error_data', views.export_historical_error_data, name='export_historical_error_data'),
    path('export_onsite_summary_data', views.export_onsite_summary_data, name='export_onsite_summary_data'),
    path('export_onsite_error_data', views.export_onsite_error_data, name='export_onsite_error_data'),
    path('export_historical_keyword', views.export_historical_keyword, name='export_historical_keyword'),
    path('user_manual', views.user_manual, name='user_manual'),
    path('historical_errorcode_result', views.historical_errorcode_result, name='historical_errorcode_result'),
    path('historical_keyword_result', views.historical_keyword_result, name='historical_keyword_result'),
    path('export_historical_errorcode_error_data', views.export_historical_errorcode_error_data, name='export_historical_errorcode_error_data'),
    path('export_osr_part_number_xlsx', views.export_osr_part_number_xlsx, name='export_osr_part_number_xlsx'),
    path('cqe_configuration', views.cqe_configuration, name="cqe_configuration"),
    path('login', views.login_view, name='login_view'),
    path('logout', views.logout_view, name="logout_view"),
    path('create_account', views.create_account, name="create_account"),
    path('approval/<int:id>',views.approval, name="approval"),
    path('osr_dashboard', views.osr_dashboard, name="osr_dashboard"),
    path('osr_search', views.osr_search, name="osr_search"),
    path('osr_material_graph', views.osr_material_graph, name="osr_material_graph"),
    path('osr_value_graph', views.osr_value_graph, name="osr_value_graph"),
    path('osr_distribution', views.osr_distribution, name="osr_distribution"),
    path('osr_unusual', views.osr_unusual, name="osr_unusual"),
    path('osr_trend', views.osr_trend, name="osr_trend"),
    path('osr_trend_result', views.osr_trend_result, name="osr_trend_result"),
    path('osr_usage', views.osr_usage, name="osr_usage"),
    path('osr_maintain', views.osr_maintain, name="osr_maintain"),
    path('osr_trend_multiple_select_week/<str:jet>', views.osr_trend_multiple_select_week, name="osr_trend_multiple_select_week"),
    path('osr_usage_multiple_select_week/<str:jet>', views.osr_usage_multiple_select_week, name="osr_usage_multiple_select_week"),
    path('export_latest_defect_mapping_table_xlsx', views.export_latest_defect_mapping_table_xlsx, name="export_latest_defect_mapping_table_xlsx"),
    path('export_latest_special_usage_rule_xlsx', views.export_latest_special_usage_rule_xlsx, name="export_latest_special_usage_rule_xlsx"),
    path('export_latest_combo_parts_list_xlsx', views.export_latest_combo_parts_list_xlsx, name="export_latest_combo_parts_list_xlsx"),
    path('export_latest_parts_price_xlsx', views.export_latest_parts_price_xlsx, name="export_latest_parts_price_xlsx"),
    path('export_osr_search_result',views.export_osr_search_result, name="export_osr_search_result"),
    path('export_osr_dashboard_last_month_result', views.export_osr_dashboard_last_month_result, name="export_osr_dashboard_last_month_result"),
    path('export_osr_dashboard_search_result', views.export_osr_dashboard_search_result, name="export_osr_dashboard_search_result"),
    path('export_osr_value_graph_search_result', views.export_osr_value_graph_search_result, name='export_osr_value_graph_search_result'),
    path('export_osr_trend_search_result', views.export_osr_trend_search_result, name='export_osr_trend_search_result'),
    path('export_osr_distribution_search_result', views.export_osr_distribution_search_result, name="export_osr_distribution_search_result"),
    path('download_documentation_pdf', views.download_pdf,  name='download_my_pdf'),
]