# Generated by Django 3.0.4 on 2020-06-04 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseNumber', models.CharField(max_length=100, verbose_name='CaseNumber')),
                ('createdDate', models.CharField(blank=True, max_length=50, null=True, verbose_name='CreatedDate')),
                ('machine_model', models.CharField(max_length=50, verbose_name='Model')),
                ('serialNumber', models.CharField(max_length=100, verbose_name='SerialNumber')),
                ('purchaseDate', models.DateField(verbose_name='PurchaseDate')),
                ('purchaseLocation', models.CharField(max_length=50, verbose_name='PurchaseLocation')),
                ('symptom', models.CharField(max_length=100, verbose_name='Symbol')),
                ('diagnosis', models.CharField(max_length=150, verbose_name='Diagnosis')),
                ('subject', models.CharField(max_length=150, verbose_name='Subject')),
                ('driver', models.CharField(max_length=200, verbose_name='Driver')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('resolution', models.CharField(max_length=100, verbose_name='Resolution')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('mailing_postal_code', models.CharField(max_length=6, verbose_name='MailingPostalCode')),
                ('odm', models.CharField(max_length=20, verbose_name='ODM')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords_category', models.CharField(max_length=100)),
                ('keywords_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SRQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_number', models.CharField(max_length=12, verbose_name='SRNumber')),
                ('sr_type', models.CharField(max_length=5, verbose_name='SRType')),
                ('createdDate', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
                ('machine_model', models.CharField(max_length=15, verbose_name='Model')),
                ('serialNumber', models.CharField(blank=True, max_length=25, null=True)),
                ('purchaseDate', models.CharField(blank=True, max_length=15, null=True)),
                ('purchaseLocation', models.CharField(blank=True, max_length=25, null=True)),
                ('errorCode', models.CharField(max_length=30)),
                ('internalNotes', models.CharField(max_length=300)),
                ('odm', models.CharField(max_length=20, verbose_name='ODM')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('population', models.PositiveIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Country')),
            ],
        ),
    ]
