# Generated by Django 3.0.4 on 2020-06-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20200604_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='srqs',
            name='predict_error_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='srqs',
            name='train',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
