# Generated by Django 3.0.4 on 2020-07-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0004_cases_predict_error_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usageDateTime', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
