# Generated by Django 3.0.4 on 2020-07-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0005_logfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='action',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='keywords_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='keywords_name',
            field=models.TextField(blank=True, null=True, verbose_name='Rule'),
        ),
    ]
