# Generated by Django 3.0.4 on 2020-07-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0006_auto_20200706_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywords',
            old_name='keywords_category',
            new_name='keywords_class',
        ),
        migrations.RenameField(
            model_name='keywords',
            old_name='keywords_name',
            new_name='keywords_rule',
        ),
    ]
