# Generated by Django 3.0.4 on 2020-07-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0007_auto_20200706_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='description',
            new_name='internalNotes',
        ),
        migrations.RenameField(
            model_name='cases',
            old_name='serialNumber',
            new_name='sr_number',
        ),
    ]
