# Generated by Django 3.0.4 on 2020-07-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0009_auto_20200708_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='sr_number',
            new_name='serial_number',
        ),
    ]
