# Generated by Django 3.0.4 on 2020-07-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0011_searchdata_casenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='symptom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='symptom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Symbol'),
        ),
    ]
