# Generated by Django 3.0.4 on 2020-07-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0012_auto_20200708_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Diagnosis'),
        ),
    ]
