# Generated by Django 3.0.4 on 2020-07-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0013_auto_20200708_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchdata',
            old_name='caseNumber',
            new_name='CaseNumber',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='createdDate',
            new_name='CreatedDate',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='data_source_type',
            new_name='Data_source_type',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='diagnosis',
            new_name='Diagnosis',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='errorCode',
            new_name='ErrorCode',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='internalNotes',
            new_name='InternalNotes',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='machine_model',
            new_name='Machine_model',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='predict_error_code',
            new_name='Predict_error_code',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='predict_partial',
            new_name='Predict_partial',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='serialNumber',
            new_name='SerialNumber',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='sr_number',
            new_name='Sr_number',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='sr_type',
            new_name='Sr_type',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='symptom',
            new_name='Symptom',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='train',
            new_name='Train',
        ),
    ]
