# Generated by Django 3.0.4 on 2020-07-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0017_auto_20200714_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
